export enum ProcedureErrorType {
    DOCTOR_NOT_AVAILABLE = 'DOCTOR_NOT_AVAILABLE',
    INVALID_DATE = 'INVALID_DATE',
    COST_VALIDATION = 'COST_VALIDATION',
    DUPLICATE_PROCEDURE = 'DUPLICATE_PROCEDURE',
    PROCEDURE_NOT_FOUND = 'PROCEDURE_NOT_FOUND',
    PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND',
    AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',
    NETWORK_ERROR = 'NETWORK_ERROR',
    SERVER_ERROR = 'SERVER_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}
